# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arhome.Email'),
        ),
        migrations.AddField(
            model_name='member',
            name='mem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arhome.Member_id'),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arhome.Name'),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arhome.Password'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arhome.Phone'),
        ),
        migrations.AddField(
            model_name='member',
            name='vid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arhome.Video_id'),
        ),
    ]
