# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhome', '0002_auto_20171119_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.SmallIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='mem_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='vid_id',
        ),
        migrations.AddField(
            model_name='member',
            name='memberID',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=70),
        ),
        migrations.DeleteModel(
            name='Member_id',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Video_id',
        ),
        migrations.AddField(
            model_name='member',
            name='videos_subscribe',
            field=models.ManyToManyField(to='arhome.videos'),
        ),
    ]
