# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arhome', '0004_auto_20171120_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='videos_subscribe',
            field=models.ManyToManyField(to='arhome.Videos'),
        ),
    ]
