entrypoint: gunicorn -b :$PORT arweb.wsgi
env: flex
runtime: python
threadsafe: yes

runtime_config:
  python_version: 3

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: main.application

beta_settings:
  cloud_sql_instances: ar-webs:us-east1:db-dev-arweb

env_variables:
  DJANGO_SETTINGS_MODULE: 'arweb.settings'   
